public class sampleClass {

public sampleClass(){
}

public void classMethod(){
    system.debug('Hello QPMSINT2');
    system.debug('Hello1 QPMSINT2');
    system.debug('Hello2 QPMSINT2');
    system.debug('Hello3 QPMSINT2');
}

public static void dummyMethod(){
  Integer dummyCounter = 1;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    dummyCounter++;
    system.debug('Hello QPMSINT2');
    system.debug('Hello QPMSINT2');
    system.debug('Hello QPMSINT2');
}

}